" Igor's vimrc 3.0, smart-ass edition

filetype plugin indent on

" no vi in my vim
if &compatible
  set nocompatible
endif

" shouldn't it be on by default? 0_o
syntax on
colorscheme jellybeans
" line numeration
set nu
set mouse=a
set nowrap
set cursorline
" persistent statusline
set laststatus=2

set history=1024
set colorcolumn=80
set foldmethod=indent
" the best option for last line tab-completion
set wildmode=list:full
set hidden

set termguicolors

" for softtabs uncomment
set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4

set cinkeys-=0#
set indentkeys-=0#

set completeopt=menu

" ======== PLUGINS ========

call plug#begin()

Plug 'NLKNguyen/papercolor-theme'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ap/vim-css-color'
Plug 'sheerun/vim-polyglot'
Plug 'jrozner/vim-antlr'

"Plug 'natebosch/vim-lsc'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'adimit/prolog.vim'
"Plug 'jdonaldson/vaxe'
Plug 'denilson-melo/vim-gdscript3'
Plug 'alunny/pegjs-vim'
Plug 'leafgarland/typescript-vim'
Plug 'wilsaj/chuck.vim'

if has('nvim')
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
endif

call plug#end()

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_theme = 'jellybeans'

"let g:lsc_enable_autocomplete = v:false
"let g:lsc_auto_map = v:true
"hi link lscDiagnosticError SpellBad

"let g:lsc_server_commands = {
    "\'javascript': 'node /home/igor/progs/js-ts-langserver/lib/language-server-stdio',
    "\'typescript': 'node /home/igor/progs/js-ts-langserver/lib/language-server-stdio',
    "\'gdscript3': 'localhost:6008'
    "\}

let g:NERDCustomDelimiters = { 'dsl': { 'left': '/*','right': '*/' } }

" ======== CUSTOM COMMANDS ========
" write with sudo
cmap w!! w !sudo tee > /dev/null %

" ======== COC.NVIM SPECIALS ========
" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

"let g:coc_global_extensions=[ 'coc-omnisharp', 'coc-tsserver', 'coc-json', 'coc-fsharp']

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
" GoTo code navigation.
nmap <silent> <leader>gd <Plug>(coc-definition)
nmap <silent> <leader>gy <Plug>(coc-type-definition)
nmap <silent> <leader>gi <Plug>(coc-implementation)
nmap <silent> <leader>gr <Plug>(coc-references)
" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" ======== HOTKEYS ========

if has('nvim')
  nnoremap <leader>ff <cmd>Telescope find_files<cr>
  nnoremap <leader>fg <cmd>Telescope live_grep<cr>
  nnoremap <leader>fb <cmd>Telescope buffers<cr>
  nnoremap <leader>fh <cmd>Telescope help_tags<cr>
endif

" toggle last search highlighting
nnoremap <silent> <c-_> :set hlsearch!<return>
" close the buffer w/o closing the window
nnoremap <c-c> :bp\|bd #<cr>
" window navigation
"nnoremap <tab> <c-w>w
"nnoremap <s-tab> <c-w>W
" save file
nmap <F2> :w<cr>
imap <F2> <esc>:w<cr>li
" buffer navigation
nnoremap <F6> :bp<cr>
vnoremap <F6> <esc>:bp<cr>
inoremap <F6> <esc>:bp<cr>i
nnoremap <F7> :bn<cr>
vnoremap <F7> <esc>:bn<cr>
inoremap <F7> <esc>:bn<cr>i
" fix syntax highlighting
noremap <F9> <Esc>:syntax sync fromstart<CR>
inoremap <F9> <C-o>:syntax sync fromstart<CR>
nmap <F10> :TlistToggle<cr>
vmap <F10> <esc>:TlistToggle<cr>
imap <F10> <esc>:TlistToggle<cr>
nmap <F11> :NERDTreeToggle<cr>
vmap <F11> <esc>:NERDTreeToggle<cr>
imap <F11> <esc>:NERDTreeToggle<cr>

" ======== SPECIAL CASES ========

autocmd BufNewFile,BufRead ~/naboo/dasha/*.json set expandtab softtabstop=2 tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead ~/naboo/dasha/*.js set expandtab softtabstop=2 tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead ~/naboo/dasha/*.ts set expandtab softtabstop=2 tabstop=2 shiftwidth=2
